workflows:
  android-debug-apk:
    name: Android Debug APK
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
    scripts:
      - name: Complete Android project files
        script: flutter create --platforms=android --org com.example .
      - name: Get packages
        script: flutter pub get
      - name: Analyze project
        script: flutter analyze
      - name: Build installable APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
